name: Build Container

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-image:
    if: ${{ hashFiles('Dockerfile') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
